# Day 1: Data Ingestion & Raw Profiling

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

# Define relative paths
raw_dir = Path('../data/raw')
print(f"Ingestion directory target: {raw_dir.resolve()}")

Ingestion directory target: E:\MutualFundAnalysis\data\raw

## 1. Directory Scan & Size Profiling

In [2]:
raw_files = sorted(list(raw_dir.glob('*.csv')))
file_details = []
for f in raw_files:
    try:
        df = pd.read_csv(f)
        file_details.append({
            "File Name": f.name,
            "Size (KB)": round(f.stat().st_size / 1024, 2),
            "Rows": df.shape[0],
            "Columns": df.shape[1]
        })
    except Exception as e:
        print(f"Error loading {f.name}: {e}")

details_df = pd.DataFrame(file_details)
details_df

                       File Name  Size (KB)   Rows  Columns
0             01_fund_master.csv       6.66     40       15
1             02_nav_history.csv    1190.99  46000        3
2       03_aum_by_fund_house.csv       3.92     90        5
3     04_monthly_sip_inflows.csv       1.63     48        6
4        05_category_inflows.csv       3.58    144        3
5    06_industry_folio_count.csv       0.80     21        6
6      07_scheme_performance.csv       6.44     40       19
7   08_investor_transactions.csv    3054.61  32778       13
8      09_portfolio_holdings.csv      23.35    322        8
9       10_benchmark_indices.csv     245.09   8050        3
10                118632_raw.csv      68.17   3314        2
11                119092_raw.csv      78.87   3581        2
12                119551_raw.csv      69.88   3252        2
13                120503_raw.csv      68.61   3323        2
14                120841_raw.csv      69.27   3317        2
15                125497_raw.csv      64.94   3107        2

## 2. Ingesting & Profiling Key Datasets

In [3]:
# Fund Master profile
fm = pd.read_csv(raw_dir / '01_fund_master.csv')
print(f"Fund Master Shape: {fm.shape}")
print("\n--- Columns and Types ---")
fm.info()
print("\n--- Sample Data ---")
fm.head(3)

Fund Master Shape: (40, 15)

--- Columns and Types ---
<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 4.8 KB

--- Sample Data ---

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03

In [4]:
# NAV History profile
nav = pd.read_csv(raw_dir / '02_nav_history.csv')
print(f"NAV History Shape: {nav.shape}")
print("\n--- Columns and Types ---")
nav.info()
print("\n--- Sample Data ---")
nav.head(3)

NAV History Shape: (46000, 3)

--- Columns and Types ---
<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.1 MB

--- Sample Data ---

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869

In [5]:
# Transactions profile
tx = pd.read_csv(raw_dir / '08_investor_transactions.csv')
print(f"Transactions Shape: {tx.shape}")
print("\n--- Columns and Types ---")
tx.info()
print("\n--- Sample Data ---")
tx.head(3)

Transactions Shape: (32778, 13)

--- Columns and Types ---
<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  str
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 3.3 MB

--- Sample Data ---

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified

## 3. Reference Mapping Validation

In [6]:
master_amfi = set(fm['amfi_code'].unique())
nav_amfi = set(nav['amfi_code'].unique())
tx_amfi = set(tx['amfi_code'].unique())

print(f"Unique AMFI codes in Fund Master: {len(master_amfi)}")
print(f"Unique AMFI codes in NAV History: {len(nav_amfi)}")
print(f"Unique AMFI codes in Transactions: {len(tx_amfi)}")

# Detect missing references
nav_orphans = nav_amfi - master_amfi
tx_orphans = tx_amfi - master_amfi

print(f"\nOrphaned AMFI codes in NAV History (not in master): {nav_orphans}")
print(f"Orphaned AMFI codes in Transactions (not in master): {tx_orphans}")
if not nav_orphans and not tx_orphans:
    print("Referential integrity checks passed! All AMFI codes map correctly.")

Unique AMFI codes in Fund Master: 40
Unique AMFI codes in NAV History: 40
Unique AMFI codes in Transactions: 40

Orphaned AMFI codes in NAV History (not in master): set()
Orphaned AMFI codes in Transactions (not in master): set()
Referential integrity checks passed! All AMFI codes map correctly.